=== CTRLab-WashU/ArcAssessmentsiOS/Arc/Resources/example_schema_grids.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "missed_session": {
      "type": "integer"
    },
    "model_version": {
      "type": "string"
    },
    "app_version": {
      "type": "string"
    },
    "session_date": {
      "type": "integer"
    },
    "session": {
      "type": "integer"
    },
    "day": {
      "type": "integer"
    },
    "start_time": {
      "type": "number"
    },
    "finished_session": {
      "type": "integer"
    },
    "device_info": {
      "type": "string"
    },
    "tests": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "grid_test": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "date": {
                  "type": "number"
                },
                "sections": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "images": {
                          "type": "array",
                          "items": [
                            {
                              "type": "object",
                              "properties": {
                                "image": {
                                  "type": "string"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "y": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "image",
                                "x",
                                "y"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "image": {
                                  "type": "string"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "y": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "image",
                                "x",
                                "y"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "image": {
                                  "type": "string"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "y": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "image",
                                "x",
                                "y"
                              ]
                            }
                          ]
                        },
                        "display_test_grid": {
                          "type": "number"
                        },
                        "display_distraction": {
                          "type": "number"
                        },
                        "display_symbols": {
                          "type": "number"
                        },
                        "choices": {
                          "type": "array",
                          "items": [
                            {
                              "type": "object",
                              "properties": {
                                "grid_selection_time": {
                                  "type": "number"
                                },
                                "y": {
                                  "type": "integer"
                                },
                                "selection": {
                                  "type": "integer"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "image_selection_time": {
                                  "type": "number"
                                },
                                "image": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "grid_selection_time",
                                "y",
                                "selection",
                                "x",
                                "image_selection_time",
                                "image"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "grid_selection_time": {
                                  "type": "number"
                                },
                                "y": {
                                  "type": "integer"
                                },
                                "selection": {
                                  "type": "integer"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "image_selection_time": {
                                  "type": "number"
                                },
                                "image": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "grid_selection_time",
                                "y",
                                "selection",
                                "x",
                                "image_selection_time",
                                "image"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "grid_selection_time": {
                                  "type": "number"
                                },
                                "y": {
                                  "type": "integer"
                                },
                                "selection": {
                                  "type": "integer"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "image_selection_time": {
                                  "type": "number"
                                },
                                "image": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "grid_selection_time",
                                "y",
                                "selection",
                                "x",
                                "image_selection_time",
                                "image"
                              ]
                            }
                          ]
                        },
                        "f_count": {
                          "type": "integer"
                        },
                        "e_count": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "images",
                        "display_test_grid",
                        "display_distraction",
                        "display_symbols",
                        "choices",
                        "f_count",
                        "e_count"
                      ]
                    },
                    {
                      "type": "object",
                      "properties": {
                        "images": {
                          "type": "array",
                          "items": [
                            {
                              "type": "object",
                              "properties": {
                                "image": {
                                  "type": "string"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "y": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "image",
                                "x",
                                "y"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "image": {
                                  "type": "string"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "y": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "image",
                                "x",
                                "y"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "image": {
                                  "type": "string"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "y": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "image",
                                "x",
                                "y"
                              ]
                            }
                          ]
                        },
                        "display_test_grid": {
                          "type": "number"
                        },
                        "display_distraction": {
                          "type": "number"
                        },
                        "display_symbols": {
                          "type": "number"
                        },
                        "choices": {
                          "type": "array",
                          "items": [
                            {
                              "type": "object",
                              "properties": {
                                "grid_selection_time": {
                                  "type": "number"
                                },
                                "y": {
                                  "type": "integer"
                                },
                                "selection": {
                                  "type": "integer"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "image_selection_time": {
                                  "type": "number"
                                },
                                "image": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "grid_selection_time",
                                "y",
                                "selection",
                                "x",
                                "image_selection_time",
                                "image"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "grid_selection_time": {
                                  "type": "number"
                                },
                                "y": {
                                  "type": "integer"
                                },
                                "selection": {
                                  "type": "integer"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "image_selection_time": {
                                  "type": "number"
                                },
                                "image": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "grid_selection_time",
                                "y",
                                "selection",
                                "x",
                                "image_selection_time",
                                "image"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "grid_selection_time": {
                                  "type": "number"
                                },
                                "y": {
                                  "type": "integer"
                                },
                                "selection": {
                                  "type": "integer"
                                },
                                "x": {
                                  "type": "integer"
                                },
                                "image_selection_time": {
                                  "type": "number"
                                },
                                "image": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "grid_selection_time",
                                "y",
                                "selection",
                                "x",
                                "image_selection_time",
                                "image"
                              ]
                            }
                          ]
                        },
                        "f_count": {
                          "type": "integer"
                        },
                        "e_count": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "images",
                        "display_test_grid",
                        "display_distraction",
                        "display_symbols",
                        "choices",
                        "f_count",
                        "e_count"
                      ]
                    }
                  ]
                }
              },
              "required": [
                "type",
                "date",
                "sections"
              ]
            }
          },
          "required": [
            "type",
            "grid_test"
          ]
        }
      ]
    },
    "participant_id": {
      "type": "string"
    },
    "week": {
      "type": "integer"
    },
    "device_id": {
      "type": "string"
    },
    "session_id": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "missed_session",
    "model_version",
    "app_version",
    "session_date",
    "session",
    "day",
    "start_time",
    "finished_session",
    "device_info",
    "tests",
    "participant_id",
    "week",
    "device_id",
    "session_id"
  ]
}

=== CTRLab-WashU/ArcAssessmentsiOS/Arc/Resources/example_data_prices.json
{"id":"1184297432549793752","missed_session":0,"model_version":"","app_version":"1.4.0","session_date":1644508800,"session":0,"day":0,"start_time":1679620675.9657919,"finished_session":1,"device_info":" iOS|x86_64|14.2","tests":[{"type":"cognitive","price_test":{"type":"priceTest","date":1679620691.263927,"sections":[{"question_display_time":33.789087057113647,"good_price":1,"price":"9.35","alt_price":"1.49","correct_index":1,"selection_time":34.65667200088501,"stimulus_display_time":0.0044200420379638672,"selected_index":0,"item":"rolls"},{"question_display_time":35.457715034484863,"good_price":1,"price":"2.87","alt_price":"9.63","correct_index":0,"selection_time":35.657956957817078,"stimulus_display_time":3.0102059841156006,"selected_index":0,"item":"lotion"},{"question_display_time":36.057978987693787,"good_price":0,"price":"7.82","alt_price":"3.62","correct_index":0,"selection_time":36.257745027542114,"stimulus_display_time":6.0142480134963989,"selected_index":0,"item":"cereal"},{"question_display_time":34.65828800201416,"good_price":0,"price":"1.73","alt_price":"5.81","correct_index":1,"selection_time":35.073873043060303,"stimulus_display_time":9.0191049575805664,"selected_index":0,"item":"light bulbs"},{"question_display_time":35.857455968856812,"good_price":1,"price":"3.74","alt_price":"1.46","correct_index":1,"selection_time":36.056424021720886,"stimulus_display_time":12.024301052093506,"selected_index":0,"item":"zucchini"},{"question_display_time":36.259497046470642,"good_price":1,"price":"8.96","alt_price":"1.75","correct_index":1,"selection_time":36.423910021781921,"stimulus_display_time":15.029793977737427,"selected_index":0,"item":"toilet paper"},{"question_display_time":35.075605034828186,"good_price":1,"price":"9.28","alt_price":"3.61","correct_index":0,"selection_time":35.254929065704346,"stimulus_display_time":18.034224033355713,"selected_index":0,"item":"celery"},{"question_display_time":36.425662040710449,"good_price":1,"price":"1.35","alt_price":"3.58","correct_index":0,"selection_time":36.624726057052612,"stimulus_display_time":21.039236068725586,"selected_index":0,"item":"blueberries"},{"question_display_time":35.659510016441345,"good_price":1,"price":"9.47","alt_price":"7.48","correct_index":1,"selection_time":35.855936050415039,"stimulus_display_time":24.045194983482361,"selected_index":0,"item":"dish soap"},{"question_display_time":35.256206035614014,"good_price":1,"price":"2.49","alt_price":"4.79","correct_index":1,"selection_time":35.456066012382507,"stimulus_display_time":27.051676034927368,"selected_index":0,"item":"pineapple"}]}}],"participant_id":"","week":0,"device_id":"CA6DCA59-D4A9-400D-98BE-9515DB9CB2EE","session_id":"1184297432549793752"}

=== CTRLab-WashU/ArcAssessmentsiOS/Arc/Resources/example_data_symbols.json
{"id":"-689279989889844462","missed_session":0,"model_version":"","app_version":"1.4.0","session_date":1644508800,"session":0,"day":0,"start_time":1679620556.16537,"finished_session":1,"device_info":" iOS|x86_64|14.2","tests":[{"type":"cognitive","symbol_test":{"type":"symbolsTest","date":1679620569.451175,"sections":[{"correct":2,"appearance_time":0.0028229951858520516,"selection_time":0.88912308216094971,"options":[["6","7"],["3","2"],["0","7"]],"selected":1,"choices":[["0","4"],["6","7"]]},{"correct":2,"appearance_time":0.89794003963470459,"selection_time":1.0218250751495361,"options":[["4","6"],["7","4"],["5","3"]],"selected":1,"choices":[["4","5"],["7","4"]]},{"correct":2,"appearance_time":1.0292010307312012,"selection_time":1.1553109884262085,"options":[["5","6"],["4","5"],["3","1"]],"selected":1,"choices":[["6","0"],["5","6"]]},{"correct":1,"appearance_time":1.1635730266571045,"selection_time":1.2886730432510376,"options":[["4","6"],["4","5"],["7","5"]],"selected":1,"choices":[["4","6"],["5","1"]]},{"correct":2,"appearance_time":1.2973400354385376,"selection_time":1.4219759702682495,"options":[["4","6"],["0","2"],["0","7"]],"selected":1,"choices":[["3","2"],["0","7"]]},{"correct":1,"appearance_time":1.4305260181427002,"selection_time":1.5379700660705566,"options":[["2","5"],["6","4"],["3","7"]],"selected":1,"choices":[["3","7"],["2","7"]]},{"correct":2,"appearance_time":1.5456219911575317,"selection_time":1.9374220371246338,"options":[["7","5"],["5","4"],["0","7"]],"selected":2,"choices":[["0","6"],["0","7"]]},{"correct":1,"appearance_time":1.9447270631790161,"selection_time":2.0888530015945435,"options":[["3","2"],["4","6"],["4","0"]],"selected":2,"choices":[["4","6"],["3","6"]]},{"correct":1,"appearance_time":2.0980310440063477,"selection_time":2.2049700021743774,"options":[["2","1"],["5","3"],["6","4"]],"selected":2,"choices":[["6","4"],["7","1"]]},{"correct":1,"appearance_time":2.2133129835128784,"selection_time":2.6385550498962402,"options":[["0","4"],["6","0"],["6","3"]],"selected":1,"choices":[["6","3"],["4","7"]]},{"correct":1,"appearance_time":2.6475110054016113,"selection_time":2.7720839977264404,"options":[["3","5"],["0","5"],["7","3"]],"selected":1,"choices":[["3","5"],["1","4"]]},{"correct":2,"appearance_time":2.7809339761734009,"selection_time":2.9056999683380127,"options":[["0","2"],["6","0"],["2","4"]],"selected":1,"choices":[["6","1"],["6","0"]]}]}}],"participant_id":"","week":0,"device_id":"CA6DCA59-D4A9-400D-98BE-9515DB9CB2EE","session_id":"-689279989889844462"}

=== CTRLab-WashU/ArcAssessmentsiOS/Arc/Resources/example_data_grids.json
{"id":"-689279989889844462","missed_session":0,"model_version":"","app_version":"1.4.0","session_date":1644508800,"session":0,"day":0,"start_time":1679620466.493099,"finished_session":1,"device_info":" iOS|x86_64|14.2","tests":[{"type":"cognitive","grid_test":{"type":"gridTest","date":1679620505.4101019,"sections":[{"images":[{"image":"key","x":1,"y":0},{"image":"pen","x":4,"y":2},{"image":"phone","x":0,"y":4}],"display_test_grid":17.02863609790802,"display_distraction":5.0148501396179199,"display_symbols":2.0117931365966797,"choices":[{"grid_selection_time":18.77220606803894,"y":0,"selection":0,"x":1,"image_selection_time":19.470639109611511,"image":"key"},{"grid_selection_time":19.955562114715576,"y":3,"selection":2,"x":3,"image_selection_time":20.653958082199097,"image":"pen"},{"grid_selection_time":17.471740126609802,"y":3,"selection":1,"x":0,"image_selection_time":18.303590059280396,"image":"phone"}],"f_count":8,"e_count":0},{"images":[{"image":"key","x":1,"y":1},{"image":"phone","x":0,"y":2},{"image":"pen","x":3,"y":4}],"display_test_grid":38.190559148788452,"display_distraction":26.182744145393372,"display_symbols":23.17937707901001,"choices":[{"grid_selection_time":40.675142168998718,"y":2,"selection":0,"x":2,"image_selection_time":41.191046118736267,"image":"key"},{"grid_selection_time":39.158290147781372,"y":2,"selection":1,"x":1,"image_selection_time":39.690413117408752,"image":"phone"},{"grid_selection_time":41.50871205329895,"y":3,"selection":2,"x":3,"image_selection_time":42.307637095451355,"image":"pen"}],"f_count":8,"e_count":0}]}}],"participant_id":"","week":0,"device_id":"CA6DCA59-D4A9-400D-98BE-9515DB9CB2EE","session_id":"-689279989889844462"}
